export const exercises = [
  { value: "chest-press", label: "Chest Press" },
  { value: "squats", label: "Squats" },
  { value: "db-curls", label: "DB Curls" },
  { value: "db-shoulder-press", label: "DB Shoulder Press" },
  { value: "db-bench-press", label: "DB Bench Press" },
  { value: "deadlifts", label: "Deadlifts" },
  { value: "pull-ups", label: "Pull-ups" },
  { value: "push-ups", label: "Push-ups" },
  { value: "lunges", label: "Lunges" },
  { value: "leg-press", label: "Leg Press" },
  { value: "bicep-curls", label: "Bicep Curls" },
  { value: "tricep-dips", label: "Tricep Dips" },
  { value: "plank", label: "Plank" },
  { value: "burpees", label: "Burpees" },
  { value: "bench-press", label: "Bench Press" },
  { value: "barbell-squats", label: "Barbell Squats" },
  { value: "lat-pulldowns", label: "Lat Pulldowns" },
  { value: "hammer-curls", label: "Hammer Curls" },
  { value: "box-jumps", label: "Box Jumps" },
  { value: "calf-raises", label: "Calf Raises" },
  { value: "front-squats", label: "Front Squats" },
  { value: "plank-twist", label: "Plank Twist" },
  { value: "seated-rows", label: "Seated Rows" },
  { value: "dumbbell-flyes", label: "Dumbbell Flyes" },
  { value: "reverse-lunges", label: "Reverse Lunges" },
  { value: "reverse-crunches", label: "Reverse Crunches" },
  { value: "romanian-deadlifts", label: "Romanian Deadlifts" },
  { value: "side-plank", label: "Side Plank" },
  { value: "sumo-deadlifts", label: "Sumo Deadlifts" },
  { value: "skull-crushers", label: "Skull Crushers" },
  { value: "hanging-leg-raises", label: "Hanging Leg Raises" },
  { value: "incline-bench-press", label: "Incline Bench Press" },
  { value: "overhead-press", label: "Overhead Press" },
  { value: "step-ups", label: "Step-ups" },
  { value: "barbell-curls", label: "Barbell Curls" },
  { value: "diamond-push-ups", label: "Diamond Push-ups" },
  { value: "fire-hydrants", label: "Fire Hydrants" },
  { value: "goblet-squats", label: "Goblet Squats" },
  { value: "leg-extensions", label: "Leg Extensions" },
  { value: "dumbbell-rows", label: "Dumbbell Rows" },
  { value: "bench-dips", label: "Bench Dips" },
  { value: "bear-crawls", label: "Bear Crawls" },
  { value: "side-lunges", label: "Side Lunges" },
  { value: "sprints", label: "Sprints" },
  { value: "bicycle-crunches", label: "Bicycle Crunches" },
  { value: "wall-sits", label: "Wall Sits" },
  { value: "tricep-kickbacks", label: "Tricep Kickbacks" },
  { value: "lying-leg-curls", label: "Lying Leg Curls" },
  { value: "bent-over-rows", label: "Bent Over Rows" },
  { value: "hip-thrusts", label: "Hip Thrusts" },
  { value: "reverse-grip-lat-pulldowns", label: "Reverse Grip Lat Pulldowns" },
  { value: "jump-rope", label: "Jump Rope" },
  { value: "cable-crossovers", label: "Cable Crossovers" },
  { value: "kettlebell-swings", label: "Kettlebell Swings" },
  { value: "side-leg-raises", label: "Side Leg Raises" },
  { value: "seated-leg-press", label: "Seated Leg Press" },
  { value: "single-leg-deadlifts", label: "Single Leg Deadlifts" },
  { value: "front-raises", label: "Front Raises" },
  { value: "standing-calf-raises", label: "Standing Calf Raises" },
  { value: "overhead-tricep-extensions", label: "Overhead Tricep Extensions" },
  { value: "single-arm-dumbbell-rows", label: "Single Arm Dumbbell Rows" },
  { value: "walking-lunges", label: "Walking Lunges" },
  { value: "bench-press-machine", label: "Bench Press Machine" },
  { value: "leg-curl-machine", label: "Leg Curl Machine" },
  { value: "leg-press-machine", label: "Leg Press Machine" },
  { value: "hack-squats", label: "Hack Squats" },
  { value: "dumbbell-pullover", label: "Dumbbell Pullover" },
  { value: "overhead-dumbbell-press", label: "Overhead Dumbbell Press" },
  { value: "lat-pull-machine", label: "Lat Pull Machine" },
  { value: "cable-row-machine", label: "Cable Row Machine" },
  { value: "stair-climber", label: "Stair Climber" },
  { value: "rowing-machine", label: "Rowing Machine" },
  { value: "elliptical-machine", label: "Elliptical Machine" },
  { value: "stationary-bike", label: "Stationary Bike" },
  { value: "swimming", label: "Swimming" },
];
